// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxXYFga4IeMVhxSSsDRElUYii5r2JixhQ',
    appId: '1:216975115743:web:055139ac196197e82cf06a',
    messagingSenderId: '216975115743',
    projectId: 'wheredoesmytimego',
    authDomain: 'wheredoesmytimego.firebaseapp.com',
    storageBucket: 'wheredoesmytimego.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxVfOOkzhGhjtAbW0IJdDECrrYBIP-SJI',
    appId: '1:216975115743:android:526c6b02ab14988e2cf06a',
    messagingSenderId: '216975115743',
    projectId: 'wheredoesmytimego',
    storageBucket: 'wheredoesmytimego.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIt6zVU-T8KclJOGqqJe-4M6KzD8hyjr4',
    appId: '1:216975115743:ios:c5872a8e739003e42cf06a',
    messagingSenderId: '216975115743',
    projectId: 'wheredoesmytimego',
    storageBucket: 'wheredoesmytimego.firebasestorage.app',
    iosBundleId: 'com.example.timeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIt6zVU-T8KclJOGqqJe-4M6KzD8hyjr4',
    appId: '1:216975115743:ios:c5872a8e739003e42cf06a',
    messagingSenderId: '216975115743',
    projectId: 'wheredoesmytimego',
    storageBucket: 'wheredoesmytimego.firebasestorage.app',
    iosBundleId: 'com.example.timeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxXYFga4IeMVhxSSsDRElUYii5r2JixhQ',
    appId: '1:216975115743:web:cc629b9ca7aef3d82cf06a',
    messagingSenderId: '216975115743',
    projectId: 'wheredoesmytimego',
    authDomain: 'wheredoesmytimego.firebaseapp.com',
    storageBucket: 'wheredoesmytimego.firebasestorage.app',
  );
}
